# Generated by Django 3.2.5 on 2021-08-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('phoneno', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
